import Foundation

enum StringCatalog {
    static let requiredKeys: [String] = [
        "home.title",
        "home.subtitle",
        "home.organize.title",
        "home.organize.subtitle",
        "home.organize.action",
        "home.organize.open",
        "home.organize.open.help",
        "home.organize.open.panel",
        "home.organize.open.prompt",
        "home.organize.disabled",
        "home.maps.loading",
        "home.maps.available %lld",
        "home.warnings.title %lld",
        "settings.title",
        "settings.language",
        "settings.language.portuguese",
        "settings.language.english",
        "settings.language.help",
        "settings.version",
        "settings.version.marketing",
        "settings.about",
        "settings.about.body",
        "common.retry",
        "error.generic",
        "error.map.invalid",
        "error.map.id.empty",
        "error.map.version",
        "error.map.name",
        "error.map.pattern.empty",
        "error.map.pattern.token",
        "error.map.inbox.folder",
        "error.map.slots.empty",
        "error.slot.id.empty",
        "error.slot.id.duplicate",
        "error.slot.folder.invalid",
        "error.slot.folder.duplicate",
        "error.slot.role.conflict",
        "error.slot.expected",
        "error.slot.expected.missing",
        "error.slot.hotkey.empty",
        "error.slot.hotkey.duplicate",
        "error.map.inbox.count",
        "error.map.inbox.mismatch",
        "error.map.trash.count",
        "error.maps.missing",
        "error.maps.empty",
        "error.maps.unreadable",
        "error.maps.decoding",
        "error.maps.invalid_file",
        "error.maps.duplicate",
        "error.filename",
        "error.slug",
        "error.project.schema",
        "error.project.map_id",
        "error.project.name",
        "error.project.decoding",
        "common.ok",
        "common.cancel",
        "common.continue",
        "common.back",
        "common.done",
        "home.recents.title",
        "home.recents.reveal",
        "home.recents.remove",
        "home.recents.remove.title",
        "home.recents.remove.listing",
        "home.recents.remove.files",
        "home.recents.remove.body %@",
        "wizard.title",
        "wizard.step %lld",
        "wizard.step.map",
        "wizard.step.details",
        "wizard.step.success",
        "wizard.map.help",
        "wizard.map.slots %lld",
        "wizard.location.label",
        "wizard.location.empty",
        "wizard.location.choose",
        "wizard.location.panel",
        "wizard.location.prompt",
        "wizard.name.label",
        "wizard.name.placeholder",
        "wizard.name.help",
        "wizard.create",
        "wizard.success.title",
        "wizard.success.body",
        "wizard.success.reveal",
        "error.wizard.map.required",
        "error.project.folder.empty",
        "error.project.folder.invalid",
        "error.project.folder.too_long",
        "error.project.create.map",
        "error.project.create.parent_missing",
        "error.project.create.parent_type",
        "error.project.create.parent_access",
        "error.project.create.exists",
        "error.project.create.failed",
        "error.project.create.metadata",
        "error.project.bookmark",
        "error.project.bookmark.resolve",
        "home.recents.open",
        "workspace.home",
        "workspace.triage.start",
        "workspace.inbox.count %lld",
        "workspace.inbox.label",
        "import.drop",
        "import.choose",
        "import.panel",
        "import.panel.prompt",
        "import.stats %lld %lld %lld %lld",
        "triage.close",
        "triage.rotate",
        "triage.trash",
        "triage.undo",
        "triage.empty",
        "shortcuts.title",
        "shortcuts.slot",
        "shortcuts.general",
        "shortcuts.trash",
        "shortcuts.nav",
        "shortcuts.rotate",
        "shortcuts.undo",
        "shortcuts.skip",
        "shortcuts.esc",
        "settings.image",
        "settings.image.size",
        "settings.image.quality",
        "settings.image.quality.high",
        "settings.image.quality.medium",
        "settings.updates.check",
        "settings.updates.help",
        "settings.updates.unconfigured",
        "settings.updates.checking",
        "settings.updates.current",
        "settings.updates.available %@",
        "settings.updates.autoCheck",
        "settings.updates.autoCheck.help",
        "settings.updates.install",
        "settings.updates.relaunch",
        "settings.updates.later",
        "settings.updates.cancel",
        "settings.updates.progress.checking",
        "settings.updates.progress.download",
        "settings.updates.progress.extract",
        "settings.updates.progress.install",
        "settings.updates.progress.ready",
        "settings.updates.installed.title",
        "settings.updates.installed.reopen",
        "settings.updates.bytes %@ %@",
        "settings.updates.released %@",
        "settings.updates.repo",
        "settings.updates.move.action",
        "settings.updates.move.help",
        "settings.updates.move.failed",
        "updates.banner.title",
        "updates.banner.body %@ %@",
        "updates.toolbar.available",
        "updates.toolbar.progress",
        "updates.sheet.close",
        "error.image.not_an_image",
        "error.image.empty",
        "error.image.write",
        "error.image.rotate",
        "error.organizer.missing",
        "error.organizer.slot",
        "error.organizer.exists",
        "error.organizer.move",
        "error.organizer.undo.empty",
        "error.organizer.index",
        "error.project.open.metadata",
        "error.project.open.map",
        "error.project.open.access",
        "error.project.delete.not_project",
        "error.project.delete.failed",
        "error.import.partial",
        "error.triage.hotkey",
        "error.updates.parse",
        "error.updates.network",
        "error.updates.location",
        "error.updates.signature",
        "error.updates.failed",
        "workspace.add_photos",
        "workspace.triage.start %lld",
        "triage.position %lld %lld",
        "status.home",
        "status.maps %lld",
        "status.recents %lld",
        "status.version %@",
        "status.update %@",
        "status.inbox %lld",
        "status.classified %lld",
        "status.review",
        "status.triage",
        "status.importing %lld %lld",
        "status.undo %lld",
        "status.slot %@",
        "workspace.slot.general",
        "workspace.slot.trash",
        "review.thumbs.smaller",
        "review.thumbs.larger",
        "review.thumbs.automatic",
        "workspace.home.hint",
        "workspace.add_photos.hint",
        "home.recents.reveal.hint",
        "workspace.triage.start.hint",
        "shortcuts.title.hint",
        "review.thumbs.smaller.hint",
        "review.thumbs.larger.hint",
        "review.thumbs.automatic.hint",
        "home.organize.action.hint",
        "home.recents.remove.hint",
        "home.recents.open.hint",
        "common.retry.hint",
        "common.ok.hint",
        "common.cancel.hint",
        "common.continue.hint",
        "common.back.hint",
        "common.done.hint",
        "wizard.create.hint",
        "wizard.location.choose.hint",
        "wizard.success.reveal.hint",
        "import.choose.hint",
        "settings.title.hint",
        "settings.updates.cancel.hint",
        "settings.updates.install.hint",
        "settings.updates.relaunch.hint",
        "settings.updates.check.hint",
        "settings.updates.move.action.hint",
        "updates.toolbar.available.hint",
        "updates.toolbar.progress.hint",
        "updates.sheet.close.hint",
        "triage.close.hint",
        "triage.rotate.hint",
        "triage.trash.hint",
        "triage.undo.hint"
    ]
}
